### ISSUE TITLE
suggestion: how about adding a new feature like a repository of useful information

### ISSUE THREAD

**Issue by monzug** [alpheios-project/documentation#20]
this idea come out when I read section 600 of Allen and Greenough grammar which explains well (and in few lines) the difference between modern and classical languages.
it would be nice if we can add such a repository of interesting 'stuff' to share
Maybe users could also submit relevant info that we can add to the repository.
the useful info can be anything relevant for learning the language or curiosities or quotes that could still have a meaning in today's crazy world.
maybe we could use evernote app

**Comment by monzug** [comment]
an other approach would be through social media. post a weekly quote on FB/Twitter to engage the alpheios community or to build a community

**Comment by monzug** [comment]
an other nice one from Plato: The ancient Greeks were never politically unified before the rise of Rome, yet they succeeded in developing and maintaining a common culture all around the Mediterranean coasts ‘like frogs around a pond’ (Plato Phaedo 109b)

**Comment by balmas** [comment]
I like the social media engagement idea but it requires a commit of resource time to do. I'll discuss with @abrasax to get his thoughts. 

In the meantime, we can continue to accumulate ideas and links here. This resource looks interesting

http://fass.open.ac.uk/classical-studies/learning-ancient-greek

**Comment by monzug** [comment]
postponed
